### ISSUE TITLE
code improvement

### ISSUE THREAD

**Issue by rlmendes** [aspnet/Docs.pt-br#108]
I suggest this improvement for this part of code:

Genre: &lt;select asp-for="MovieGenre" asp-items="Model.Genres"&gt;
            &lt;option value=""&gt;All&lt;/option&gt;
        &lt;/select&gt;
Just for better appearance for users.

Thanks

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: cc54dbf8-e6fe-a212-b2cd-c015a6ba5439
* Version Independent ID: b96b0b44-3e3a-a6c2-6b2b-c7bab4b78f0d
* Content: [Adicionar a pesquisa às Páginas Razor do ASP.NET Core](https://docs.microsoft.com/pt-br/aspnet/core/tutorials/razor-pages/search?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/search.md](https://github.com/aspnet/docs.pt-br/blob/live/aspnetcore/tutorials/razor-pages/search.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by CeciAc** [comment]
Issue moved to [aspnet/Docs #11357](https://github.com/aspnet/Docs/issues/11357) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @rlmendes 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/aspnet/Docs/issues/11357

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
