### ISSUE TITLE
AddMemoryCache is no more required

### ISSUE THREAD

**Issue by joelrlneto** [aspnet/Docs.pt-br#109]
In my recent tests, it was not necessary to call the method `services.AddMemoryCache()` inside `ConfigureServices`. For some reason, the IMemoryCache is being injected correctly and the memory cache is working well. But I did not find any updated documentation that says calling `AddMemoryCache `is no more required.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 13f5f8f9-18dd-9c12-9ed1-fcc6b44ba7fd
* Version Independent ID: 640b4f36-5886-7b69-1c95-cfc8574a02fd
* Content: [Memória de cache no ASP.NET Core](https://docs.microsoft.com/pt-br/aspnet/core/performance/caching/memory?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/performance/caching/memory.md](https://github.com/aspnet/Docs.pt-br/blob/live/aspnetcore/performance/caching/memory.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-performance**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by CeciAc** [comment]
Hello, @joelrlneto

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/aspnet/AspNetCore.Docs/issues/11835

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
